spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_test?Unicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useAffectedRows=true
    username: root
    password: root

  redis:
    host: 172.16.1.16
    database: 6