spring:
  profiles:
    active: dev
  application:
    name: demo

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-enums-package: org.jz.demo.spring.enums




