spring:
  redis:
    host: 172.16.1.16
    database: 6

  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://172.16.1.13:3306/db_test?Unicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useAffectedRows=true
        username: jiayoubao
        password: root1234
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://172.16.1.13:3306/db_test2?Unicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useAffectedRows=true
        username: jiayoubao
        password: root1234
    sharding:
      default-data-source-name: ds0
      tables:
        t_coupon_account:
          actual-data-nodes: ds${0..1}.t_coupon_account_${0..1}
          database-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: ds${user_id % 2}
          table-strategy:
            inline:
              sharding-column: user_id
              algorithm-expression: t_coupon_account_${user_id % 2}
      binding-tables:
        - t_coupon_account
    props:
      sql.show: true