spring:
  datasource:
    url: jdbc:mysql://172.16.1.13:3306/db_jyb_test?Unicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&useAffectedRows=true
    username: jiayoubao
    password: root1234